### ISSUE TITLE
Can you provide a fully working example app?

### ISSUE THREAD

**Issue by chakrit** [BlakeWilliams/Elixir-Slack#1]
I'm new to elixir, and having followed your example running `mix run` on the project seems to cause it to prints out a hello message but then the app finishes, and the bot disconnects. I know this may sound tedious, but it'd be nice if you could provide a fully working example application (sans the Slack token) so I can compare and see what I did wrong. This'd also help other Elixir newbies to get going quickly as well.

**Comment by BlakeWilliams** [comment]
I think you want to run `mix run --no-halt` so the process doesn't die.

I wrote https://github.com/BlakeWilliams/CleverSlack which should be a more complete example.

**Comment by BlakeWilliams** [comment]
Closing this, let me know if further examples would help!

**Comment by chakrit** [comment]
Just saw this, thanks for putting that up : )
