### ISSUE TITLE
do we expect send_message to work with private channels?

### ISSUE THREAD

**Issue by gvaughn** [BlakeWilliams/Elixir-Slack#105]
My company recently converted a channel that my bot was working with to a private channel. Now I'm finding this error when it tries to send a message to slack:

```
[error] expected a map, got: nil
[error]     (stdlib) :maps.find(:id, nil)
[web.1]:     (elixir) lib/map.ex:145: Map.get/3
[web.1]:     (slack) lib/slack/sends.ex:10: Slack.Sends.send_message/3
[web.1]:     (bot) lib/bot/slack.ex:46: Bot.Slack.handle_info/3
[web.1]:     (slack) lib/slack/bot.ex:99: Slack.Bot.websocket_info/3
```

My code is basically doing
```
handle_info(my_message, slack, state) do
  send_message("my message", "#mychannel", slack)
  {:ok, state}
end
```

Perhaps my real issue that I can't refer to private channels simply with the `#` prefixed name. If anyone has insights, I'd appreciate it.

**Comment by BlakeWilliams** [comment]
Hmmm, I bet that function is only looking through public channels. I'd happily take a PR that looks through both public and private channels.

**Comment by gvaughn** [comment]
Thanks for the speedy reply! As I'm trying to poke around, all I'm seeing from `Slack.Web.Channels.list` are public channels. I need to put the pieces together on how to find and refer to a private channel. When the bot is invited to the private channel it replies just fine, but when I try to process async messages to the bot, it can't send to the channel. I use `message.channel` when replying, but `"#mychannel"` in those async calls.

Might be a few days before I could put together a PR, if that's even the right approach. I suspect the bot is only allowed to reference private channels it's invited to and I'm just navigating the Slack API wrong.

**Comment by BlakeWilliams** [comment]
According to the docs private channels are stored in `groups`, which we do track. So we could probably try to fallback to groups.

**Comment by gvaughn** [comment]
Right. I got something working for my immediate needs using `groups`. I think the fallback is a good choice. People logically still think of private channels like `#mychannel` even though the Slack API distinguishes them as groups. If the bot has been invited into the `group`, then the fallback seems like the principle of least surprise to the developer. I expect to have some time early next week to generalize what I've done into a PR. Thanks for your insight.

**Comment by gvaughn** [comment]
I had time sooner than expected! https://github.com/BlakeWilliams/Elixir-Slack/pull/106

**Comment by gvaughn** [comment]
@BlakeWilliams I hate to be "that guy" asking about his PR, but ... well ... have you had a look at it? If you'd release a new hex package, I could pull that in and clean up my app's code and have one less thing on my mental to-do list. If it's not meeting project style guidelines or something, let me know and I'll clean it up.

**Comment by BlakeWilliams** [comment]
Nope, it just fell off my radar is all. I'll take a look!

**Comment by BlakeWilliams** [comment]
0.10.0 was released. :)

**Comment by gvaughn** [comment]
Thanks! I'm off to LonestarElixir Conf tomorrow, but maybe I can fit in time for some Elixir hacking while I'm there :-)
