### ISSUE TITLE
How to add this to a supervisor tree?

### ISSUE THREAD

**Issue by jaimeiniesta** [BlakeWilliams/Elixir-Slack#109]
This post has a nice example for building a Slack bot with this library:

https://medium.com/carwow-product-engineering/getting-started-writing-a-slack-bot-with-elixir-b8877072f038

But it fails when it comes to adding it to a supervisor tree, for example in a Phoenix app.

What's the proper way of doing it?

**Comment by BlakeWilliams** [comment]
That example is likely based on an older version of the library. Something along the lines of the following will probably work:

```
worker(Slack.Bot, [MyApp.Bot, [], "API_TOKEN"])
```
