### ISSUE TITLE
Write a "fake slack" for integration testing

### ISSUE THREAD

**Issue by BlakeWilliams** [BlakeWilliams/Elixir-Slack#111]
Currently testing in the application works, but it's not ideal.

What would be great to have is a fake slack server that we can spin up and have an actual bot interact with it.

This would also be good to at least smoke test the web API modules that are generated.

**Comment by jhulten** [comment]
So not a recorded test set like https://github.com/parroty/exvcr ?

**Comment by BlakeWilliams** [comment]
That would be difficult for the RTM part since it's websockets.

I have a PR open for it in #112 if you were interested in it. (I should have mentioned this issue on it tbf)

**Comment by BlakeWilliams** [comment]
For the generated web API, that could be useful because it's hand-tested at the moment.

**Comment by dhurley14** [comment]
This [1] might be of help.. Haven't used it myself. I was looking to see how I could run integration tests for slack and I came across this.

[1]: https://github.com/codeforequity-at/testmybot
