### ISSUE TITLE
Elixir-Slack converts slack API response keys to atoms

### ISSUE THREAD

**Issue by davydog187** [BlakeWilliams/Elixir-Slack#114]
Atoms are [not garbage collected](https://github.com/elixir-lang/elixir/issues/2915#issuecomment-65556180) in the BEAM vm, so converting strings to atoms in the slack API response is dangerous.

Consider changing the Elixir-Slack API contract to use strings as keys rather than converting them to atoms.

Relevent code: 
* https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/rtm.ex#L17
* https://github.com/BlakeWilliams/Elixir-Slack/blob/1dbd554bb632c3bf5c523b44f0376ad19e378de8/lib/slack/sends.ex#L82
* https://github.com/BlakeWilliams/Elixir-Slack/blob/228988b65b89ffb1f4fdc7af5265546c1c0d6024/lib/slack/bot.ex#L147

**Comment by BlakeWilliams** [comment]
I think this is a good idea, I'd happily take a PR for this.

**Comment by acconrad** [comment]
No longer relevant since this is off of `JSX` and is not decoding to `:atoms` anymore
