### ISSUE TITLE
Consider replacing exjsx with Poison

### ISSUE THREAD

**Issue by davydog187** [BlakeWilliams/Elixir-Slack#115]
Elixir-Slack currently uses exjsx for json parsing, however this project doesn't have great documentation, and [Poison](https://github.com/devinus/poison) has a lot more traction with the community.

If you think this is a good idea, I would be happy to make these changes.

**Comment by BlakeWilliams** [comment]
This was on my internal todo list, I'd happily accept a PR if anyone wants to tackle this before I have time to get this in.

**Comment by BlakeWilliams** [comment]
Done in #119
