### ISSUE TITLE
Superfluous_charset warnings

### ISSUE THREAD

**Issue by dschniepp** [BlakeWilliams/Elixir-Slack#127]
When I use the post_message api:
```
Slack.Web.Chat.post_message("#general", "test", %{attachments: [%{pretext: "pre-hello", text: "text-world"}] |> Poison.encode! })
```
I get a __superfluous_charset__ warning.
```
"response_metadata" => %{
  "warnings" => ["superfluous_charset"]
}
```
Due to https://api.slack.com/methods/chat.postMessage it seems to be a missing __content-type__, is there a way to set this via the api?

**Comment by Sitch** [comment]
Seems like you just need to pass the content type as an option to `HTTPoison.post/2` in the `Slack.Sends.open_im_channel/4`.  Would be nice to be able to set a decent default, likely `"utf-8"`, bc emojis :).  The only other supported option is `"iso-8859-1"` which is a single byte encoding for pure text.

**Comment by BlakeWilliams** [comment]
I'd happily accept a PR setting `utf-8` as the encoding for those endpoints (or all, given how the code is structured).

**Comment by tckb** [comment]
Is there any workaround for this issue?

**Comment by acconrad** [comment]
@sitch @dschniepp @tckb the fix is in this PR
