### ISSUE TITLE
compile slack error on ubuntu

### ISSUE THREAD

**Issue by tt67wq** [BlakeWilliams/Elixir-Slack#130]
05:50:21.184 [error] Loading of /data/slack-robot/ebot/_build/dev/lib/jsx/ebin/jsx_config.beam failed: :badfile

05:50:21.184 [error] beam/beam_load.c(1287): Error loading module jsx_config:
  mandatory chunk of type 'Atom' not found

== Compilation error on file lib/slack/web/web.ex ==

05:50:21.221 [error] Loading of /data/slack-robot/ebot/_build/dev/lib/jsx/ebin/jsx_config.beam failed: :badfile

05:50:21.221 [error] beam/beam_load.c(1287): Error loading module jsx_config:
  mandatory chunk of type 'Atom' not found

** (UndefinedFunctionError) function :jsx_config.extract_config/1 is undefined (module :jsx_config is not available)
    :jsx_config.extract_config([])
    lib/jsx.ex:14: JSX.decode!/2
    lib/slack/web/web.ex:12: anonymous fn/2 in Slack.Web.format_documentation/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/slack/web/web.ex:25: (file)

**Comment by BlakeWilliams** [comment]
Can you provide more details? What version of Elixir, Erlang, and Ubuntu are you running?

**Comment by davydog187** [comment]
@BlakeWilliams can you release the latest master? exjsx/jsx should no longer be a dependency
