### ISSUE TITLE
post_message with attachments is not working

### ISSUE THREAD

**Issue by DmitryKK** [BlakeWilliams/Elixir-Slack#131]
I create following request for example:

`Slack.Web.Chat.post_message("D5LDLCNF3", "hello", %{ attachments: %{  text: "Choose answer" } }, token: "token" })`

As a result, I got following error:

```
** (ArgumentError) argument error
          :erlang.list_to_binary([%{text: "Choose answer"}])
```

I couldn't resolve problem. I need help, please

**Comment by BlakeWilliams** [comment]
@DmitryKK Do you need to turn `attachments` into JSON?

**Comment by ivanovaleksey** [comment]
@DmitryKK why did you close the issue?
