### ISSUE TITLE
Update websocket_client dependency

### ISSUE THREAD

**Issue by ivanovaleksey** [BlakeWilliams/Elixir-Slack#137]
Hi @BlakeWilliams, thanks for the great project!

I noticed that `websocket_client` dependency version is `1.1.0` but is was released September 16, 2015. It is almost 2 years now.

Can we update the version?

**Comment by benbotwin** [comment]
This is actually needed as older versions of `websocket_client` don't work with newer versions of erlang

see: https://github.com/jeremyong/websocket_client/issues/49

**Comment by BlakeWilliams** [comment]
I can get to this eventually, but if it's important I'd accept a PR and can cut a release sooner rather than later.

**Comment by benbotwin** [comment]
I just made a PR. All the tests passed and I was able to get the rtm bot going without any issues #138

**Comment by BlakeWilliams** [comment]
Just pushed `0.12.0` that has #138.
