### ISSUE TITLE
lookup_user_name fails for user_id that starts with a W

### ISSUE THREAD

**Issue by tomekr** [BlakeWilliams/Elixir-Slack#139]
A year ago, Slack changed their user id strings and some user IDs may now begin with the letter "W"

From the [API documentation](https://api.slack.com/types/user): 

> The id field is a string identifier for this team member. It is only unique to the team containing the user. Use this field instead of the name field when storing related data or when specifying the user in API requests. Though the ID field usually begins with U, it is also possible to encounter user IDs beginning with W. We recommend considering the string an opaque value. [Read more](https://api.slack.com/changelog/2016-08-11-user-id-format-changes) about recent changes to user ID strings.

The `Slack.Lookups`'s `lookup_user_name` function checks only for a `U` (see  
https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/lookups.ex#L50)

**Comment by mmartinson** [comment]
Ya this probably could use a patch to be compliant with the suggestion from the API docs you linked. 

[Here is the code](https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/lookups.ex#L50) if someone wants to have a go at it.

**Comment by jameskbride** [comment]
Thanks for this awesome project! I put together a quick PR to address this.  See PR https://github.com/BlakeWilliams/Elixir-Slack/pull/186.

**Comment by jameskbride** [comment]
https://github.com/BlakeWilliams/Elixir-Slack/pull/188 addresses this.
