### ISSUE TITLE
send message with attachment 

### ISSUE THREAD

**Issue by DinaWork** [BlakeWilliams/Elixir-Slack#143]
So I defined a module that uses the Slack behaviour and defines the appropriate callback methods.

```
{:ok, rtm} = Slack.Bot.start_link(SlackRtm, [], "token")
send rtm, {:message, "hello world", "#general"}
```
works well for me, and I receive "hello world" messages in general channel .
how can I send messages  with attachments as described [here]( https://api.slack.com/docs/message-attachments)?

**Comment by BlakeWilliams** [comment]
Have you looked at the [`Slack.Web.Chat` documentation](https://hexdocs.pm/slack/Slack.Web.Chat.html#post_message/3)?

I haven't tested it, but that's probably your best bet. The real time API does not support attachments from what I remember.

**Comment by DinaWork** [comment]
thanks, that's exactly what I was looking for!

**Comment by ajose01** [comment]
@BlakeWilliams speaking of which... the documentation doesn't make mention of encoding the attachment bit to json. (Unless I missed it :( )

Do you take PR's around clarifying API usage? I've been working with your hex for the past couple days, so if I find other things that I think could help others I'd love to contribute.

**Comment by BlakeWilliams** [comment]
@ajose01 I do! It might be difficult given how the web documentation is generated but if you can get it working I'd happily accept it.

**Comment by BlakeWilliams** [comment]
Sounds like this was resolved, closing
