### ISSUE TITLE
Web API: Proposed breaking change before 1.0 - comments wanted

### ISSUE THREAD

**Issue by mmartinson** [BlakeWilliams/Elixir-Slack#146]
The web API, though quite fully featured in its support, is currently somewhat limited in its semantics in that are function calls [assume the happy path](https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/web/web.ex#L51) and return only correct data/raise a number of different possible exceptions. This may be fine in some situations for simple apps, but for production apps that need to handle and report on different sorts of error combinations it would be very valuable to have more of both consistency and control here.

I'm not sure I really see an easy way around this without breaking the current API, so this is a suggestion to break it while this library is still pre-1.0. Let's have a discussion here with anybody that cares and figure out how it might work best.

### Proposal 1 - Tagged tuples

For < 400 status, decode response body from JSON and return `{:ok, decode_response}`

For other cases, define a series of exception structs in the format Slack.Web.*Error and return in the format `{:error, exception}`. These could wrap HTTPoison exceptions like timeouts, as well as more slack specific exceptions like [429 rate limit](https://api.slack.com/docs/rate-limits) (this is one I care about a lot). 

This approach would allow all error cases to be mapped into a consistent format that could report on, and have conditional retry logic in place for certain cases.

### Proposal 2 - Move Slack.Web to different repo as dependency.

If breaking this API is problematic for enough people, a reasonable approach could be to move everything in Slack.Web into a different open source project (which could potentially start with the tagged tuple approach immediately after code migration). The project could provide the same interface to web API calls as it current does by unwrapping the tagged responses are raising error errors passed back.

It could be useful if doing this to consider incorporating any overlap from [the other slack API client](https://github.com/davidstump/slackex/issues/7) which is currently a stale/dead project and is the one listed in [the slack API community page](https://api.slack.com/community#elixir)

@BlakeWilliams @JEG2 @christhekeele @davydog187 @timabdulla and others, would be great to get your feedback.

**Comment by BlakeWilliams** [comment]
@mmartinson I like the first proposal, it's honestly something that the library should have already been doing but doesn't (thanks to me). I'd definitely accept PR's making error handling for the web client better.

As for the second proposal, we're pre-1.0 so I don't think we should worry too much about backwards compatibility. My first thoughts are to keep the web + RTM API's together for now, but I'm definitely open to hearing others thoughts on it as well.

Also thanks a ton for writing this up, this is extremely helpful in terms of guiding the project towards a bright(er) future.

**Comment by JEG2** [comment]
@BlakeWilliams sounds wise to me.  😄

**Comment by mmartinson** [comment]
Great. I can get started working on this. I need to investigate the rate limiting for a product I'm working on, so I'll make some changes and put up a WIP PR for folks to comment on.

**Comment by acconrad** [comment]
@mmartinson I can implement this - do you have a rough idea of where this should be added?

**Comment by acconrad** [comment]
Closing as this is over 3 years old and no one has responded to move forward in over 3 months
