### ISSUE TITLE
Update RTM connection API call to handle user presence deprecation

### ISSUE THREAD

**Issue by mmartinson** [BlakeWilliams/Elixir-Slack#147]
From the [Slack API docs](https://api.slack.com/docs/presence-and-status)

> Batched presence events
>
> Traditionally, using the Real Time Messaging API the initial call to rtm.start or rtm.connect would include the current presence value for every member of your workspace. If their presence value changes after that, a presence_change event would be sent.
>
> Now presence events must be batched together into a special version of the presence_change event that includes a users array instead of a singular user field. You must enable this new behavior by passing the batch_presence_aware=true parameter to rtm.start or rtm.connect. presence_change events will otherwise no longer be sent after November 15, 2017.
>
> Initial presence state will no longer be described when connecting to rtm.start.

If we want to continue to receive presence change events, we'll need to modify the `rtm.start` call to pass the specified parameter.

**Comment by mmartinson** [comment]
It seems like Slack didn't ship on schedule, because I've still been getting presence change events after the 15th and didn't make this change. Anyone else depending on this presence info for key functionality?

**Comment by nrw505** [comment]
I am, and I have https://github.com/BlakeWilliams/Elixir-Slack/pull/153 to address it.

**Comment by nrw505** [comment]
Also https://github.com/BlakeWilliams/Elixir-Slack/pull/154 for a related presence issue.

**Comment by obrok** [comment]
I'd really like to see this (these?) merged - I'm using the presence functionality, and it seems slack finally did ship this a couple days ago

**Comment by mmartinson** [comment]
Thanks @nrw505. Your fix does it.

**Comment by obrok** [comment]
@mmartinson could you post in this issue once you release?
