### ISSUE TITLE
Sending attachments in messages

### ISSUE THREAD

**Issue by dapdizzy** [BlakeWilliams/Elixir-Slack#148]
Sending attachments is messages (on behalf of Bot) is apparently missing.

There is a note that sending attachments **is not supported for RTM API**.
However, some Ruby examples and the general structure of message containing attachments does not seem to contradict with the way textual messages are sent. So, unless there's some strict contradiction, it seems to be just a missing feature for Elixir-Slack API.

Please consider implementing a function allowing to send messages with attachments or justify why it is not possible to implement in this API.

**Comment by BlakeWilliams** [comment]
> Please consider implementing a function allowing to send messages with attachments or justify why it is not possible to implement in this API.

The generated web API might have support for this via: https://hexdocs.pm/slack/Slack.Web.Chat.html

Otherwise I'm happy to accept a PR building out that functionality.
