### ISSUE TITLE
API docs repo is dead

### ISSUE THREAD

**Issue by pezra** [BlakeWilliams/Elixir-Slack#150]
Currently, the web API client is missing many features because https://github.com/slackhq/slack-api-docs isn't being updated.  According to https://github.com/slackhq/slack-api-docs/issues/74 we should expect it to remain dead.

Should we move off generating the web API function from JSON? We could define DSL to make defining calls to those remote procedures easier.

I have a specific need for https://api.slack.com/methods/chat.getPermalink which is not currently provided by `Slack.Web`. Would you merge a PR that added that feature via code (rather than JSON files)?

**Comment by BlakeWilliams** [comment]
This is a great point, and a great question.

Given that the API docs repo is dead and there's no alternative I think migrating towards rolling our own DSL (or just functions) is the path forward.

**Comment by pezra** [comment]
OK. I'll see if i can find the time to implement the call i need as straight code and we'll see where that leads. 😄

**Comment by hwrd** [comment]
There is a new Slack API docs repo based on OpenAPI! https://github.com/slackapi/slack-api-specs

**Comment by BlakeWilliams** [comment]
@hwrd Woah that's awesome! Thanks for the headsup on that.

**Comment by mmartinson** [comment]
I tried using the swagger client generator for elixir to build a client the other day. It has a bunch of syntax errors from the generated code.

**Comment by acconrad** [comment]
@hwrd looks like that package is out of date as well, missing stuff like the `views.*` methods - if I can avoid manually writing them that would be great, though it sounds like [this](https://github.com/slackapi/slack-api-specs/issues/29#issuecomment-543255200) could be a solution

**Comment by acconrad** [comment]
Closing since I've been adding methods manually - if you need a method just let me know
