### ISSUE TITLE
Versioning: README vs mix.envs vs Hex vs Releases

### ISSUE THREAD

**Issue by blue-dinosaur** [BlakeWilliams/Elixir-Slack#159]
Hello, I am confused about the versioning.

The last release is 0.10, the README shows 0.12, the code shows 0.14 in mix.exs.

Could anyone please clarify? Thanks in advance!

**Comment by BlakeWilliams** [comment]
Sometimes things just don't get updated or get missed. :)

I pushed the latest tag + updated the README. Thanks for letting me know!
