### ISSUE TITLE
Bump HTTPoison to non-ancient version

### ISSUE THREAD

**Issue by honkycat** [BlakeWilliams/Elixir-Slack#168]
Your current httpoison version is from Jan 8, 2017, making it over a year old.

**Comment by BlakeWilliams** [comment]
I don't have much time to do this right now, but I'd happily accept a PR.

**Comment by BlakeWilliams** [comment]
Fixed in #170

**Comment by Swingcloud** [comment]
since dependencies has been updated, maybe can jump the version to 0.14.1 let mix can get latest deps? thanks 🙇

**Comment by BlakeWilliams** [comment]
`0.15.0` should be out now
