### ISSUE TITLE
Include (or link to) examples of usage

### ISSUE THREAD

**Issue by twilco** [BlakeWilliams/Elixir-Slack#178]
It would be nice if there were some examples of usage in an `examples` directory or in a separate repo.  These examples would serve as a valuable (and different) form of documentation, and would help future users visualize ways in which they might use this library.

**Comment by pavellishin** [comment]
I'm very interested in using this library to practice me some Elixir, so once I get underway, I'd be glad to link to my examples, or add some to the documentation - but work and personal issues are eating my fun programming time right now :(
