### ISSUE TITLE
Crash upon start

### ISSUE THREAD

**Issue by binaryseed** [BlakeWilliams/Elixir-Slack#181]
Hi there! https://github.com/BlakeWilliams/Elixir-Slack/pull/177 introduces a bug that causes the app to crash upon start...

See the https://github.com/BlakeWilliams/Elixir-Slack/pull/177#issuecomment-461811475

```
** (EXIT from #PID<0.323.0>) shell process exited with reason: an exception was raised:
    ** (KeyError) key :bots not found in: %{ok: true, self: %{...}, team: %{...}, url: "..."}
        (slack) lib/slack/bot.ex:90: Slack.Bot.init/1
        (websocket_client) /.../deps/websocket_client/src/websocket_client.erl:164: :websocket_client.init/1
        (stdlib) gen_fsm.erl:351: :gen_fsm.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

cc/ @acconrad @BlakeWilliams @aquarhead

**Comment by axelson** [comment]
I'm seeing this too. Using this as the `slack` dependency works for me:

```
{:slack, github: "BlakeWilliams/Elixir-Slack", ref: "4812cf8"},
```

**Comment by BlakeWilliams** [comment]
Interesting. I’ll look into this soon and revert and re-release or pull the existing release if necessary.

**Comment by acconrad** [comment]
This was my release. This is based on the `rtm.start` method which includes `bots` now as a property https://api.slack.com/methods/rtm.start

**Comment by acconrad** [comment]
@binaryseed @axelson @BlakeWilliams I've got a tentative fix open with #184 I just need some guidance to get the tests passing and then we should be good to go

**Comment by perzanko** [comment]
I have the same issue 😎

**Comment by acconrad** [comment]
@perzanko are you on the latest version? it should be resolved now via #190

**Comment by axelson** [comment]
But do note that there isn't a release with that change yet, so you'd have to use master directly. @BlakeWilliams is it possible to cut another release with the fix?

**Comment by BlakeWilliams** [comment]
@axelson `0.19.0` was released that includes that change I believe. I'll update the README and push the tag.

**Comment by axelson** [comment]
Ah, I see. Didn't notice that release I guess. Thanks for updating the readme and pushing the tag!

**Comment by perzanko** [comment]
@acconrad @axelson @BlakeWilliams Now it works - THANKS 👍
