### ISSUE TITLE
Token generation instructions incomplete

### ISSUE THREAD

**Issue by axelson** [BlakeWilliams/Elixir-Slack#182]
Judging by the instructions present in the readme does this library only support legacy tokens?

Edit: Sent early

Legacy tokens:
https://api.slack.com/docs/token-types#legacy

If not are there any instructions to go from: "App ID", "Client ID", "Client Secret", "Signing Secret" to the  "token" that `Slack.Bot.start_link` expects?

**Comment by yulolimum** [comment]
I'm not sure if this helps you, but you can get the oauth token after you grant your Slack app permissions and install it:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/1775841/54469195-414d8300-4752-11e9-8b7e-ea63a50daacd.png">

**Comment by axelson** [comment]
Thanks! That was what I was missing.

Note: you need to go to the "Your Apps" page: https://api.slack.com/apps, click on your app, then click on "Add features and functionality ", then click on the "Permissions" button, and then you can get your oauth access token.

**Comment by BlakeWilliams** [comment]
If it's possible to make this more clear in the README I'd love a PR if anyone has time. :)

**Comment by axelson** [comment]
Created #183!
