### ISSUE TITLE
Missing tags and releases for versions after v0.15.0

### ISSUE THREAD

**Issue by dideler** [BlakeWilliams/Elixir-Slack#197]
The last Git tag and [GitHub release](https://github.com/BlakeWilliams/Elixir-Slack/releases) is at v0.15.0.

 Hex shows there's been four releases since
- 0.19.0 April 18, 2019
- 0.18.0 April 14, 2019
- 0.17.0 April 14, 2019
- 0.16.0 December 31, 2018

Could the tags and releases be updated please? Makes referencing and comparisons easier.

**Comment by BlakeWilliams** [comment]
Yeah, my mistake there. I just pushed up any tags that were missing and on my machine but I think it might only include 0.19.0.

Unless anyone really requires it I'm going to skip on backfilling previous versions since this is pre-1.0.

Thanks!
