### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dideler** [BlakeWilliams/Elixir-Slack#198]
Consider introducing a CHANGELOG.md file for users to review changes easily.

The lack of a changelog combined with #197 makes upgrading the library tricky.<sup>[1]</sup>

If you're unsure of what format to use, I recommend
- [Keep a Changelog](https://keepachangelog.com)
- or, the [Elixir core convention](https://github.com/elixir-lang/elixir/blob/master/CHANGELOG.md) of a summary followed by enhancements, bug fixes, soft deprecations (no warnings), hard deprecations, and breaking changes

---

1. Fortunately the latest version of Hex, [v0.20](https://hex.pm/blog/hex-v0.20-released), introduced a tool to help review changes.  
   ```
   mix hex.package diff slack 0.15.0..0.19.0 | colordiff | less
   ``` 
   Can upgrade to the latest Hex version by running `mix local.hex`.

**Comment by BlakeWilliams** [comment]
I personally love changelogs but it's not something I have the time to maintain. If/when the library hits 1.0 I'll likely be more disciplined about maintaining a changelog given the commitment to a public API.

Thanks for the suggestion!
