### ISSUE TITLE
Chat.schedule_message

### ISSUE THREAD

**Issue by nathany** [BlakeWilliams/Elixir-Slack#205]
Hi. I'm not seeing support for scheduling messages. Is it there and just not documented? What would it take to add this?

https://api.slack.com/methods/chat.scheduleMessage

**Comment by nathany** [comment]
If implemented, would the API take a Unix timestamp like the Slack endpoint, or would it take a DateTime and do the `to_unix` conversion?

**Comment by nathany** [comment]
Do [these JSON files](https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/web/docs/chat.postMessage.json) come from somewhere or are they being crafted based on the documentation?

What else needs to be done to add a function?

**Comment by acconrad** [comment]
@nathany the way I've done it is to add those JSON files directly into that folder. The API is pretty out of date, lots of stuff needs to be added in there or updated

**Comment by acconrad** [comment]
@nathany see #212 as to how I did it - you can do the exact same for this and just create a file `chat.scheduleMessage.json`
