### ISSUE TITLE
Hex has elixir-slack version with poison 3.0

### ISSUE THREAD

**Issue by ahsandar** [BlakeWilliams/Elixir-Slack#206]
https://diff.hex.pm/diff/slack/0.19.0..0.20.0

**Comment by acconrad** [comment]
What is the issue here? I see there is a diff, but `Elixir-Slack` was only _just_ bumped to version `0.20.0` - are you sure you weren't forking off of another branch or a PR?

**Comment by ahsandar** [comment]
its updated now , wasn't showing up iunitially when reported. thanks
`"slack": {:hex, :slack, "0.20.0", "87852885884546441e81cd2b96edc2ea966c306a345386503722d5c17a2aad70", [:mix], [{:httpoison, "~> 1.2", [hex: :httpoison, repo: "hexpm", optional: false]}, {:poison, "~> 3.0", [hex: :poison, repo: "hexpm", optional: false]}, {:websocket_client, "~> 1.2.4", [hex: :websocket_client, repo: "hexpm", optional: false]}], "hexpm"},`
