### ISSUE TITLE
Add travis to check builds

### ISSUE THREAD

**Issue by afaur** [BlakeWilliams/Elixir-Slack#21]
Add travis to repository to check builds.  This will enable..
- An indication if tests are passing on new Pull Requests.
- Indicator to show status of tests against the master branch on the top of the README.

**Comment by afaur** [comment]
Looks like travis may not be completely set up yet.  
Notes are here: https://github.com/BlakeWilliams/Elixir-Slack/pull/23

**Comment by BlakeWilliams** [comment]
Looks good now. https://travis-ci.org/BlakeWilliams/Elixir-Slack/builds/86522160
