### ISSUE TITLE
Upcoming slack change

### ISSUE THREAD

**Issue by nacengineer** [BlakeWilliams/Elixir-Slack#211]
Audit of how this upcoming slack change is going to affect this library. 

https://medium.com/slack-developer-blog/more-precision-less-restrictions-a3550006f9c3

I started working though updating the permissions only to get to the last page where this was thrown up.  

```The RTM API is not accessible to updated Bot Tokens. If your app requires RTM functionality, please exit this update and continue using your existing scopes.```

Not sure how updating permissions will affect my bot if I use this library.

 I think I'll be okay but wanted more knowledgeable minds to weigh in on it. I did create some functionality that uses [this setup](https://github.com/BlakeWilliams/Elixir-Slack#rtm-bot-usage)

**Comment by acconrad** [comment]
@nacengineer the only Web API method used is `rtm.connect`. `Slack.Rtm` and `Slack.Bot` I don't believe have scope access so I _think_ it's just that one call.
