### ISSUE TITLE
[Feature Request] Support unfurl method

### ISSUE THREAD

**Issue by vip30** [BlakeWilliams/Elixir-Slack#237]
Provide custom unfurl behavior for user-posted URLs

refs: https://api.slack.com/methods/chat.unfurl

And here is the mr https://github.com/BlakeWilliams/Elixir-Slack/pull/238

Thanks

**Comment by BlakeWilliams** [comment]
I don't have much time to spend on this, but I'd happily accept a pull request for this functionality.

**Comment by acconrad** [comment]
Merged in #238 nice work!
