### ISSUE TITLE
Moving ownership to BEAM community

### ISSUE THREAD

**Issue by aef-** [BlakeWilliams/Elixir-Slack#251]
Hi Blake!

I hope you're doing well. I'm not sure if you're still maintaining this repo, but if not, or even if you plan to make updates, would you consider speaking with the individuals at https://github.com/beam-community to see if they'd be willing to adopt this library? I think it's a pretty essential library and I'd really hate to see it collect dust.

**Comment by zoedsoupe** [comment]
so, I tried to make contact with them too but no answer. So I started to rewrite this library, as the same don't seem to handle the new events API and API methods.
https://github.com/zoedsoupe/slack_ex

**Comment by BlakeWilliams** [comment]
Hey, sorry for the delay in response.

I'm not actively maintaining the library anymore, but if anyone from the community is interested in starting to update the library I'd happily give folks maintainer/commit access if they were serious about it. I don't have much time to reach out to beam-community about it, but if they'd like to fork the library and continue maintaining it I'd fully support that.

**Comment by aef-** [comment]
Hey @BlakeWilliams thanks for getting back to me -- I'm happy to help maintain this library as I need some updates for a current project. I think until we find the right team/organization to take over this library and the Hex package, we should continue to push to this fork considering how many other forks there are with various updates that perhaps we can roll-in. Let me know what you think.

**Comment by zoedsoupe** [comment]
@aef- Actually I want ask your oponion about my ideia: I thought to rewrite (or update and upgrade this lib) to be like [bolt-js](https://github.com/slackapi/bolt-js) or the [python sdk](https://slack.dev/python-slack-sdk/)

However I have some doubts:
1. should the lib mantain support to old apps with RTM ?
2. should the lib map Slack API - maybe with `ecto` - entities?
3. a DSL to create bots gets outside of this lib scope?
4. could we use `Phoenix.Channel` to handle websocket?

**Comment by aef-** [comment]
@zoedsoupe I'm really just interested in finding a way to keep this package maintained at the moment. I'll be updating my fork with potential breaking changes. If there's a scenario in which I can get them merged and published to Hex, I'll consider making them backwards compatible.

**Comment by zoedsoupe** [comment]
@aef- ok then, I'll be watching and following your fork, maybe I could contribute too, however I'll try to implement those ideas beacuse of my different needs

**Comment by BlakeWilliams** [comment]
> Hey @BlakeWilliams thanks for getting back to me -- I'm happy to help maintain this library as I need some updates for a current project.

I'd be happy to give you commit access if you'd like to take that on. It'd be great for the library to see some updates, especially if we can maintain some backwards compatibility (within reason).

**Comment by aef-** [comment]
That sounds good @BlakeWilliams, happy to help out.

**Comment by BlakeWilliams** [comment]
Closing this out since it sounds like we have a path forward.
