### ISSUE TITLE
Posting a message (not as a response)

### ISSUE THREAD

**Issue by mfilej** [BlakeWilliams/Elixir-Slack#29]
I'd like to use this library to post a simple message to a given channel (not as a response to another message – for the sake of simplicity let's say I want to trigger it myself from `iex`).

Is this something that is supported? It seems like I could use `send_message`, but then I don't know where to get (or how to construct) the Slack argument.

I'm afraid that there is an obvious answer to this but I can't figure it out because I'm too new to the ecosystem. If that's the case I hope you'll excuse me for using Issues as a support channel.

**Comment by BlakeWilliams** [comment]
Under the hood we delegate `websocket_info/3` messages to your bots `handle_info/3` function.

https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack.ex#L109-L112

This means from `iex` you could do something like: `send pid, {:say, "hello", "foo"}` (make sure you have the bots pid or registered process name as `pid`) and in your bot implementation have something along the lines of:

```
def handle_info({:say, message, channel_name}, slack, state) do
  channel_id = slack.channels |> Map.values |> Enum.find(fn(channel) -> channel.name == channel_name) |> Map.get(:id)

  send_message(message, channel_id, slack)
  {:ok, state}
end
def handle_info(_message, _slack, state), do: {:ok, state}
```

Let me know if that's helps.

**Comment by mfilej** [comment]
Thanks for the reply!

I tried implementing what you suggested and I'm getting an error. I see from where in `websocket_client` it is getting triggered but I can't quite understand the reason.

```
iex(1)> {:ok, pid} = Mybot.start_link(token, [])
iex(1)> send pid, {:say, "hi", "bot-test"}

** (EXIT from #PID<0.403.0>) {:handler, :function_clause}
iex(1)> [error] ** Websocket handler Meola.Bot terminating
** for the reason {:handler, :function_clause}
** Handler state was …
```

From what I can tell `handle_info` is not getting called at all (I tried simplifying it down to an `IO.inspect`),

**Comment by BlakeWilliams** [comment]
It looks like that change wasn't pushed to hex yet. Can you try upgrading to `0.4.0` and try again?

**Comment by mfilej** [comment]
It worked! Thank you very much for your support. :sparkling_heart:

**Comment by madshargreave** [comment]
Hey

I updated to 0.4.0, but I also receive the same error

```
mix.exs
     {:slack, "~> 0.4.0"},
     {:websocket_client, git: "https://github.com/jeremyong/websocket_client"}
    ]
  end
```

**Comment by jeshocarmel** [comment]
I'm facing the same error. 

```
defmodule Rumble.SlackRtm do
  use Slack

  def init(initial_state, slack) do
    IO.puts "Connected as #{slack.me.name}"
    {:ok, initial_state}
  end
 
  def handle_message({:type, "message", response}, slack, state) do
    state = state ++ [response.text]

    message = "Received #{length(state)} messages so far!"
    Slack.send(message, response.channel, slack)

    {:ok, state}
  end

  def handle_message({:type, type, _response}, _slack, state) do
    {:ok, state}
  end
end
```
The I execute and get the error as follows. 
```
iex(1) SlackRtm.start_link(token,[])
{:ok, #PID<0.552.0>}
iex(2)> ** (EXIT from #PID<0.543.0>) {:handler, :function_clause}
iex(2)>
iex(2)> [error] ** Websocket handler Rumble.SlackRtm terminating
** for the reason {:handler, :function_clause}
** Handler state was %{slack: %{bots: %{"B14RGHW2G" => %{deleted: false, id: "B14RGHW2G",
```

I'm using slack 0.4.2 along with websocket as deps
