### ISSUE TITLE
Retrieving the reply for send_message

### ISSUE THREAD

**Issue by madshargreave** [BlakeWilliams/Elixir-Slack#31]
Hi

As noted here

https://api.slack.com/rtm

"Once the JSON has been sent to the server visual clients should immediately display the text in the channel, grayed out or otherwise marked to indicate that it is "pending". At some point after that, usually a few milliseconds later, the server will send a confirmation that the message was received:"

As it does not seem to be caught in any of the handlers, how can I retrieve this reply?

**Comment by acconrad** [comment]
Closing since, per Slack's docs:

> New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.

source: https://api.slack.com/rtm
