### ISSUE TITLE
Loosing connection does not trigger handle_close

### ISSUE THREAD

**Issue by madshargreave** [BlakeWilliams/Elixir-Slack#33]
Hey

If I connec to the Slack RT API, and afterwards disconnects my internet, the `handle_close` callback is never called.

```
def handle_close(reason, slack, state) do
    Logger.info "[#{state.token}] Closing Slack session. Reason: #{reason}"
    {:ok, state}
  end
```

I want to be able to perform some cleanup, and then restart the connection, if it fails at any point

**Comment by BlakeWilliams** [comment]
Ah, I think we'll need to handle `websocket_terminate/3` which will be a different callback. I'll open a PR for that and get it merged.

**Comment by BlakeWilliams** [comment]
Actually, it looks like we already handle that.

If it's not getting called it's likely that [websocket_client](https://github.com/jeremyong/websocket_client) isn't triggering `websocket_terminate`.

**Comment by BlakeWilliams** [comment]
I just tried this out locally and my bot reconnected immediately. Maybe that's what it's doing under the hood? If that's the case I think this is fine to close.
