### ISSUE TITLE
Changing the Slack state?

### ISSUE THREAD

**Issue by madshargreave** [BlakeWilliams/Elixir-Slack#34]
Hi

Is the slack state automatically synced behind the scenes? Ie. will the state of a user in the Slack construct automatically update based on incoming presense_changed events, or will I have to manually update this myself?

In case of the latter, how do I update the Slack state from the handlers?

**Comment by BlakeWilliams** [comment]
Yes, it should be handled for you. https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/handlers.ex

If there's something missing please create an issue or PR for it.

**Comment by madshargreave** [comment]
I want to perform some action when the presence of a user changes, how can I hook into this callback?

**Comment by BlakeWilliams** [comment]
This gets called in `handle_message`.

eg:

```
def handle_message(message = %{type: "presence_change"}, _slack, state) do
  {:ok, state}
end
```
