### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by madshargreave** [BlakeWilliams/Elixir-Slack#35]
Hi

I don't receive any events related to typing indicators or user presence changes

Are these caught somewhere else?

**Comment by BlakeWilliams** [comment]
You can listen for this using `handle_message/3`. There's an example in #34.

Here's a list of the Slack RTM API's messages you can listen for https://api.slack.com/rtm

**Comment by madshargreave** [comment]
Yeah I know

I have defined the following callback

```
def handle_message(message, slack, state) do
    if Dict.has_key?(message, :subtype) do
      handle_message_subtype(message)
    else
      case message.type do
        "message"         -> handle_new_message(message)
        "presence_change" -> handle_presence_change(message)
        _                 -> IO.puts "Unhandled message type: #{message.type}"
      end
    end
    {:ok, state}
  end
```

But I never receive typing indicators (in the catchall) or presence_changes

**Comment by BlakeWilliams** [comment]
The following works for me on `0.4.0` as the only defined `handle_message/3` function.

```
  def handle_message(message, _slack, state) do
    case message.type do
      "presence_change" -> IO.puts "CHANGED"
      _ -> IO.puts "other"
    end
    {:ok, state}
  end
```

If you're still running into the issue, please post the rest of the code if possible.
