### ISSUE TITLE
How to handle events?

### ISSUE THREAD

**Issue by Oxyrus** [BlakeWilliams/Elixir-Slack#44]
I've been trying to handle events in my app, however I can't manage them to work. For instance, I can't manage the team_join event to work and welcome the new member

```elixir
def handle_message(message = %{type: "team_join"}, slack, state) do
    send_message("Welcome, young alchemist", message.channel, slack)
    {:ok, state}
end
```

Same goes with every event here https://api.slack.com/rtm , what is the right way to handle them?

Thank you in advance!

**Comment by Oxyrus** [comment]
With help of Daniel Grieve managed it to work

```elixir
def handle_message(%{type: "team_join"}, slack, state) do
    send_message("Welcome, young alchemist", "GENERAL_CHANNEL_ID", slack)
    {:ok, state}
end
```
Still have to find a way to get the general channel id automatically instead of hardcoding it.

**Comment by BlakeWilliams** [comment]
I think you should be able to use `Enum.find/3` on `slack.channels`. You might want to `Map.values/1` it first since it's indexed by channel id.

**Comment by Oxyrus** [comment]
I'll give it a try, thank you!

**Comment by Oxyrus** [comment]
@BlakeWilliams would it be possible to just use the channel name as indicated on the Slack API docs?

> Post to a public channel
You can either pass the channel's name (#general) or encoded ID (C024BE91L), and the message will be posted to that channel. The channel's ID can be retrieved through the channels.list API method.

I tried but didn't work.

**Comment by BlakeWilliams** [comment]
I have not, but #55 should fix this.
