### ISSUE TITLE
Sending too many requests results in obscure error

### ISSUE THREAD

**Issue by madshargreave** [BlakeWilliams/Elixir-Slack#45]
Hi

If you send too many RTM connection requests, you will eventually receive the following response

`You are sending too many requests. Please relax.`

which due to being plain text and not JSON (response.body doesnt exist), fails with following error 

```
ArgumentError) argument error
        (jsx) src/jsx_decoder.erl:234: :jsx_decoder.value/4
      (exjsx) lib/jsx.ex:15: JSX.decode!/2
      (slack) lib/slack/rtm.ex:8: Slack.Rtm.start/1

```

**Comment by BlakeWilliams** [comment]
Thanks for reporting this, this should be a quick fix.

Any chance you'd want to make a PR for this? I can help guide you on where / what to change if you'd like. If not I can make write a fix for it.

**Comment by thbar** [comment]
FWIW I won't have time for a PR on this right now, yet here is my experimental code which is not finalized but handles that specific error well at least, in case it helps anyone.

For the record, for me the error `You are sending too many requests. Please relax.` comes as content type `text/html`, with status code `429`.

```elixir
defmodule Slack.Rtm do
  @moduledoc false
  @url "https://slack.com/api/rtm.start?token="
  require Logger
  
  def start(token) do
    case HTTPoison.get(@url <> token) do
      {:ok, response} ->
        case response do
          %HTTPoison.Response{body: body, headers: %{"Content-Type" => "application/json"}} ->
            json = JSX.decode!(response.body, [{:labels, :atom}])
            {:ok, json}
          %HTTPoison.Response{body: body} ->
            # NOTE: it would be better to propagate the status code as well
            {:error, response.body}
        end
      {:error, reason} -> {:error, reason}
    end
  end
end
```
