### ISSUE TITLE
Example send_message from outside a handler

### ISSUE THREAD

**Issue by micahwedemeyer** [BlakeWilliams/Elixir-Slack#53]
It's a bit of a head-scratcher to figure out how to call `send_message`, particularly how to include the `slack` parameter. It's easy if you're in an event handler, but what if you want to send a message in response to something non-slack related (ie. "A new user just signed up!")

I'd love an example that shows how to catch and store the resulting `slack` parameter from the init and then retrieve and use it for future calls to `send_message`

**Comment by BlakeWilliams** [comment]
Does #25 help?

I wouldn't mind a pull request adding an example to the README.

**Comment by micahwedemeyer** [comment]
Here's what I came up with. I'll submit a PR, but I really hesitate to tell others to do this. I'm so new to Elixir/Erlang, and I'm probably doing something terrible with ETS here. It's probably a horrible violation of statelessness.

```
defmodule Myapp.SlackBot do
  use Slack

  def handle_connect(slack, state) do
    :ets.new(:slack_state, [:named_table])
    |> :ets.insert({"slack", slack})

    {:ok, state}
  end

  # Sends a message on the "general" channel
  def send_general_message(message) do
    [{"slack", slack}] = :ets.lookup(:slack_state, "slack")

    # Probably some fancier pattern matching way to do this...
    general = slack.channels
    |> Map.values
    |> Enum.find(&(&1[:is_general]))

    send_message(message, general.id)
  end

  def send_message(message, channel) do
    [{"slack", slack}] = :ets.lookup(:slack_state, "slack")
    send_message(message, channel, slack)
  end
end

# Somewhere else
MyApp.SlackBot.send_general_message("This will go into general")
```

**Comment by BlakeWilliams** [comment]
From #25:

> like send(:slack, {user, messge}) (assuming :slack is a registered pid that has use Slack) and letting the slack process manage all communication to users.

You can register the pid and use `send` to send messages to your bot. It will then use [`handle_info/3`](https://github.com/BlakeWilliams/Elixir-Slack/pull/25/files#diff-3e0c0ac63fea5d69355e7f178ebcdbe4R148) to respond to the message.

eg: `send(:slack, {:message, "Hello!", "12345"})` you'd have something like:

```elixir
defmodule Myapp.SlackBot do
  def handle_info({:message, text, channel}, slack, state) do
    send_message(text, channel, slack)
    {:ok, state}
  end
  def handle_info(_, _, state), do: {:ok, state}
end
```

That's a rough example, but should work.

**Comment by micahwedemeyer** [comment]
Okay, I think I understand. It's part of a Phoenix app, and I've got it starting up as a worker under a supervisor, so I think I can just register the `:slack` name for that worker and then get it using the `handle_info` as you've suggested.

I'll try to find a chance to get that done today and send an updated PR with a better README.

**Comment by BlakeWilliams** [comment]
That sounds correct to me.

Excited to see the updated PR! 😃
