### ISSUE TITLE
Turn Slack map into struct

### ISSUE THREAD

**Issue by BlakeWilliams** [BlakeWilliams/Elixir-Slack#57]
The "slack" state is currently a map but would be better as a struct so it can be better documented and functions that manipulate/interact with it can be separated from the rest of the code.

**Comment by christhekeele** [comment]
Was thinking about taking on a couple of these issues. For this one, do you want to turn `Slack` itself into a struct, or put it somewhere else to avoid cluttering the macro-ful module, like `Slack.Conn`?

**Comment by christhekeele** [comment]
Also, how do you feel other structs, like `Slack.Message`, `Slack.User`. `Slack.Channel`, etc?

**Comment by BlakeWilliams** [comment]
I would move the `Slack` state first, but it would probably be in its own module. I was initially thinking `Slack.State` but could be convinced of other names.

I think once that's done it'll make sense to re-evaluate the idea of `Slack.Message`, user, etc.

**Comment by christhekeele** [comment]
Both `Slack.Struct` and `Slack.State` seem a little nondescript, but I can't think of a great alternative. `Slack.Client` seems okay, `Slack.API` kind of inaccurate.

**Comment by christhekeele** [comment]
Alternatively, flip it around such that the state is a `%Slack{}` struct and library gets consumed with `use Slack.API` (or `Slack.Behaviour`, `Slack.Client`)

**Comment by christhekeele** [comment]
`Slack.State` feels pretty weird because all the callbacks end up with a `Slack.State` and a user-defined `state` right next to each other.

**Comment by BlakeWilliams** [comment]
I don't think it's too weird. 'Slack.Client' isn't bad either.
