### ISSUE TITLE
message.channel is not a human readable. 

### ISSUE THREAD

**Issue by Lugghawk** [BlakeWilliams/Elixir-Slack#71]
I'm not sure if this is a side effect of my slack server or something else, but my channel names appear to be things like "A123B456" instead of "general". This makes sending messages to a direct channel really challenging.

In the readme.md, during the send_message example, you used "general" there and that doesn't appear to work for me because the general channel is named something else.

**Comment by BlakeWilliams** [comment]
@Lugghawk I think it needs to be `#general` according to https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/sends.ex.

Feel free to open a PR fixing it in the README, or I can get to it later.

**Comment by Lugghawk** [comment]
Opened PR #72 for it @BlakeWilliams

**Comment by BlakeWilliams** [comment]
Fixed in #72
