### ISSUE TITLE
Websocket handler Mentioner.Slack terminating

### ISSUE THREAD

**Issue by denispeplin** [BlakeWilliams/Elixir-Slack#75]
I've got this error:

```
iex(1)> 
13:36:39.175 [error] ** Websocket handler Mentioner.Slack terminating
** for the reason {:handler, %RuntimeError{message: "argument error"}}
** Handler state was %{slack: %{bots: ...
```

Main process was still alive, but bot has gone offline. That probaly was due to missing internet connection, but I'm not sure.
Bot source code is here: https://github.com/denispeplin/mentioner

**Comment by BlakeWilliams** [comment]
I think this particular issue should be fixed in the current version of the app.
