### ISSUE TITLE
Please update readme

### ISSUE THREAD

**Issue by brweber2** [BlakeWilliams/Elixir-Slack#8]
The code samples in the README have a few minor issues:

* the match should be on %{type: "message"} in the handler and not a two value tuple
* it should be message.channel and not response.channel
* do not call start_link at compile time

Here is an actual example that worked for me.  This can be run with 

```bash
mix run --no-halt
```

```elixir
defmodule MyBot do

  use Slack

  def handle_message(message = %{type: "message"}, slack, state) do
    send_message("hello world", message.channel, slack)
    {:ok, state}
  end

  def handle_message(message, _slack, state) do
    {:ok, state}
  end

  def start(_type,_args) do
    MyBot.start_link("<YOUR API KEY GOES HERE>", [])
  end

end
```

**Comment by BlakeWilliams** [comment]
Good catch! I dropped the ball when updating the README.

I updated it to work, but I think it's worth keeping `start_link` in the example. If you have a better way of explaining / showing that I'd love to hear it.

**Comment by BlakeWilliams** [comment]
Actually, I added those two tidbits in. Thanks for opening the issue!

**Comment by brweber2** [comment]
You are still missing the % on the map. :)

Thanks for updating the docs!

**Comment by BlakeWilliams** [comment]
Gah! Thanks again! :smile:
