### ISSUE TITLE
Pass arguments into server

### ISSUE THREAD

**Issue by dax0** [BlakeWilliams/Elixir-Slack#80]
I may be missing something but I find the API of this library a bit awkward.  If I want to forward the messages received by this process to another one I need to be able to pass in a PID that's saved in the state.  There doesn't seem to be a way to set the state on handle_info, it's getting overwritten somehow. It seems I have to resort to using name PIDs everywhere which isn't ideal

Any ideas?

**Comment by BlakeWilliams** [comment]
Check out [`Process.register/2`](http://elixir-lang.org/docs/stable/elixir/Process.html#register/2) instead of using a PID.

If you need to handle state, use the [`Agent`](http://elixir-lang.org/docs/stable/elixir/Agent.html) module.

**Comment by dax0** [comment]
Named processes aren't ideal when your application has more than one instance of this Slack client running.  It becomes necessary to pass in some data to let it know how to things different depending upon certain variables.  An Agent could work but then all instances of this client need to speak to the same one and it quickly becomes a bottleneck.  

Ideally the "slack" portion of the state should be nested underneath the actual state so it doesn't overwrite everything.  handle_info, handle_call, handle_cast becomes useless otherwise.

**Comment by BlakeWilliams** [comment]
There is no `handle_call` or `handle_info` because this lib is for managing a connection to slack and reacting to it.

Maybe storing data or references in ets would help your use case?

**Comment by dax0** [comment]
Since the Slack macro is a gen_server I'd expect it to behave like a gen_server - which it does.  I can handle calls, casts, and info, except they silently don't work.

I would like to avoid ETS as well because that is similar to Agents, it starts moving private data useful only to an individual actor into a more global state.  Starts to get messy when you're dynamically spawning many Slack connections.  

Another way to deal with this is to do what the Websocket library you're using does and ask for a callback Module to specify.  That library is similar, it is for managing a connection and reacting to it yet it allows for maximum flexibility

**Comment by BlakeWilliams** [comment]
> Since the Slack macro is a gen_server I'd expect it to behave like a gen_server - which it does. I can handle calls, casts, and info, except they silently don't work.

It's not a gen_server. It's using [websocket_client](https://github.com/jeremyong/websocket_client).

> Another way to deal with this is to do what the Websocket library you're using does and ask for a callback Module to specify. That library is similar, it is for managing a connection and reacting to it yet it allows for maximum flexibility

I've been meaning to look into that (delegating to another module) but haven't had time lately. It's on the radar though.

**Comment by BlakeWilliams** [comment]
@dax0 I've started https://github.com/BlakeWilliams/Elixir-Slack/pull/86 which should be more like what you were thinking. Feel free to leave any feedback you have there.
