### ISSUE TITLE
:error:{:badmap, {:message, "testing", "#channel"}} - When trying to use handle_info

### ISSUE THREAD

**Issue by micahwedemeyer** [BlakeWilliams/Elixir-Slack#90]
In the README, it says you can use the Slack bot to send messages from other in-app events using handle_info, like so

    {:ok, rtm} = Slack.Bot.start_link(SlackRtm, [], "token")
    send rtm, {:message, "External message", "#general"}

This gives me a badmap error, which I believe is related to https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack/bot.ex#L98

It's expecting a Map, not a tuple. Am I missing something here?

**Comment by micahwedemeyer** [comment]
And if I call it like so, it works:

    {:ok, rtm} = Slack.Bot.start_link(SlackRtm, [], "token")
    send rtm, %{type: "message", text: "External message", channel: "#general"}

I have to redefine my handle_info like so, which is probably wrong:

    def handle_info(%{type: "message", text: text, channel: channel}, slack, state) do

**Comment by alanwilhelm** [comment]
The existing docs led me to the same conclusion.

**Comment by BlakeWilliams** [comment]
Huh, this looks wrong. I'll try to work on a fix soon, unless someone else wants to take a stab at it.

**Comment by micahwedemeyer** [comment]
How do you want it to work? As per the docs, or as it is right now?
Although, I don't think there's much I can do, as I am really clueless
about the internal workings of this thing.

**Comment by BlakeWilliams** [comment]
I think the `type` check from `handle_event` mistakenly made it into there. I think the conditional needs to be removed and `{:ok, %{state | process_state: new_process_state}}` should probably be put in the `try`.

**Comment by BlakeWilliams** [comment]
So it should match the docs.

**Comment by samsonasu** [comment]
I ran into this same thing today and took a stab at a fix.  I agree the syntax in the docs is better.
